
services:
  oracleserver:
    image: oracle/database:11.2.0.2-xe
    container_name: oracle11
    restart: always
    shm_size: '1gb'
    environment:
      - TZ=Asia/Shanghai
      - ORACLE_PWD=11gxe123
    ports:
      - '2023:1521'
      - '8082:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./oradata:/u01/app/oracle/oradata
